spring.application.name=user-service

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs/user-service
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.path=/user/swagger-ui.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=very_secret_key_very_secret_key_very_secret_key