spring.application.name=order-service

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs/order-service
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.path=/order/swagger-ui.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true