spring.application.name=product-service

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs/product-service
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.path=/product/swagger-ui.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true