spring.application.name=inventory-service

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs/inventory-service
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.path=/inventory/swagger-ui.html

spring.kafka.bootstrap-servers=kafka:9092

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
